import type { Metadata } from "next";

import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="en">
      <body className="bg-gradient-to-b from-[#FFB2DF] to-[#FF67C0] h-full">
        {children}
      </body>
    </html>
  );
}
